from datetime import date
from git_to_doc.model import CommitDoc, PRDoc
from git_to_doc.theme import c as _c, BOLD, DIM, GREEN, BRIGHT, section, rule


_SECTION = {
    "feat":     "Added",
    "fix":      "Fixed",
    "docs":     "Documentation",
    "refactor": "Changed",
    "perf":     "Performance",
    "test":     "Tests",
    "chore":    "Maintenance",
    "ci":       "CI/CD",
    "build":    "Build",
    "revert":   "Reverted",
}

def render_commit_message(doc: CommitDoc) -> str:
    """Returns a Conventional Commit string, e.g. feat(scope): subject"""
    scope    = f"({doc.scope})" if doc.scope else ""
    breaking = "!" if doc.breaking else ""
    header   = f"{doc.type}{scope}{breaking}: {doc.subject}"

    parts = [header]
    if doc.body:
        parts.append(f"\n{doc.body}")
    if doc.breaking:
        parts.append(f"\nBREAKING CHANGE: {doc.body or doc.subject}")
    return "\n".join(parts)


def render_changelog(doc: CommitDoc) -> str:
    """Returns a markdown changelog snippet ready to paste into CHANGELOG.md"""
    today   = date.today().isoformat()
    heading = "Breaking Changes" if doc.breaking else _SECTION.get(doc.type, "Changed")

    lines = [
        f"## [Unreleased] — {today}",
        "",
        f"### {heading}",
        "",
        doc.changelog_entry,
    ]
    if doc.body:
        lines += ["", f"  {doc.body}"]
    return "\n".join(lines)


def render_full_output(doc: CommitDoc) -> str:
    """Pretty-prints the full terminal output with colour and markdown blocks."""
    commit_msg = render_commit_message(doc)
    changelog  = render_changelog(doc)

    return f"""
{section("commit message")}

  {_c(commit_msg, BOLD, BRIGHT)}

{section("changelog entry")}
{_c("  paste into CHANGELOG.md", DIM)}

{changelog}

{section("plain english")}

  {_c(doc.plain_english, GREEN)}

{rule()}
"""


def render_pr_body(doc: PRDoc) -> str:
    """Markdown PR body (what gets posted to GitHub)."""
    lines = ["## Summary", "", doc.summary, "", "## Changes", ""]
    lines += [f"- {c}" for c in doc.changes]
    lines += ["", "## Test Plan", "", doc.test_plan]
    if doc.breaking:
        lines += ["", "## Breaking Changes", "",
                  "This PR introduces breaking changes to public behaviour."]
    lines += ["", "---", "_Generated by git-to-doc_"]
    return "\n".join(lines)


def render_pr_full_output(doc: PRDoc) -> str:
    """Pretty terminal preview of the generated pull request."""
    breaking = _c("  ! breaking changes", BOLD, BRIGHT) + "\n\n" if doc.breaking else ""
    return f"""
{section("pull request title")}

  {_c(doc.title, BOLD, BRIGHT)}

{section("pull request body")}
{_c("  markdown", DIM)}

{render_pr_body(doc)}

{breaking}{rule()}
"""


def render_markdown_file(doc: CommitDoc, model: str = "gemma4",
                          source: str = "", stats: dict = None) -> str:
    """Returns a rich markdown file with metadata, no heading collision."""
    commit_msg = render_commit_message(doc)
    today      = date.today().isoformat()
    heading    = "Breaking Changes" if doc.breaking else _SECTION.get(doc.type, "Changed")
    scope_str  = f"({doc.scope})" if doc.scope else ""

    # Files changed block
    files_block = ""
    if stats and stats.get("files"):
        files_list = "\n".join(f"- `{f}`" for f in stats["files"])
        files_block = f"""## Files Changed

{files_list}

**+{stats.get('additions', 0)} additions / -{stats.get('deletions', 0)} deletions**

---

"""

    source_block = f"> **Source:** {source}\n\n" if source else ""

    body_block = f"\n> {doc.body}\n" if doc.body else ""

    return f"""# `{doc.type}{scope_str}`: {doc.subject}

> Generated by **git-to-doc** using `{model}` on {today}
{source_block}
---

## Plain English Summary

{doc.plain_english}

---

## Conventional Commit Message

```
{commit_msg}
```

---

## Changelog Entry

### {heading}

{doc.changelog_entry}
{body_block}
---

{files_block}## Metadata

| Field | Value |
|-------|-------|
| Type | `{doc.type}` |
| Scope | `{doc.scope or "—"}` |
| Breaking Change | {"Yes" if doc.breaking else "No"} |
| Model | `{model}` |
| Generated | {today} |
"""

